# Generated by Django 4.2.4 on 2023-08-15 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=10)),
                ('Aadhar', models.IntegerField()),
                ('PAN', models.CharField(max_length=20)),
                ('Contact', models.IntegerField()),
                ('Balance', models.FloatField()),
                ('Account_Type', models.CharField(max_length=15)),
            ],
        ),
    ]
